### PR TITLE
Update waf

### PR DESCRIPTION
**Pull request by pdesaulniers**
I needed to update waf in order to get the plugins to build on Arch Linux. Otherwise, I'd get the following error:
```
Traceback (most recent call last):
  File "/tmp/bitrot/.waf3-2.0.4-91d6a4e5781350f87eb0a75b95b84884/waflib/Node.py", line 342, in ant_iter
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/bitrot/.waf3-2.0.4-91d6a4e5781350f87eb0a75b95b84884/waflib/Scripting.py", line 118, in waf_entry_point
    run_commands()
  File "/tmp/bitrot/.waf3-2.0.4-91d6a4e5781350f87eb0a75b95b84884/waflib/Scripting.py", line 174, in run_commands
    parse_options()
  File "/tmp/bitrot/.waf3-2.0.4-91d6a4e5781350f87eb0a75b95b84884/waflib/Scripting.py", line 157, in parse_options
    ctx.execute()
  File "/tmp/bitrot/.waf3-2.0.4-91d6a4e5781350f87eb0a75b95b84884/waflib/Options.py", line 198, in execute
    super(OptionsContext,self).execute()
  File "/tmp/bitrot/.waf3-2.0.4-91d6a4e5781350f87eb0a75b95b84884/waflib/Context.py", line 84, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/tmp/bitrot/.waf3-2.0.4-91d6a4e5781350f87eb0a75b95b84884/waflib/Context.py", line 125, in recurse
    user_function(self)
  File "/tmp/bitrot/wscript", line 17, in options
    opt.load('compiler_cxx')
  File "/tmp/bitrot/.waf3-2.0.4-91d6a4e5781350f87eb0a75b95b84884/waflib/Context.py", line 82, in load
    fun(self)
  File "/tmp/bitrot/.waf3-2.0.4-91d6a4e5781350f87eb0a75b95b84884/waflib/Tools/compiler_cxx.py", line 40, in options
    opt.load_special_tools('cxx_*.py')
  File "/tmp/bitrot/.waf3-2.0.4-91d6a4e5781350f87eb0a75b95b84884/waflib/Context.py", line 326, in load_special_tools
    lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
  File "/tmp/bitrot/.waf3-2.0.4-91d6a4e5781350f87eb0a75b95b84884/waflib/Node.py", line 358, in ant_glob
    return list(it)
RuntimeError: generator raised StopIteration
```

### CODE REVIEW

**Comment by pdesaulniers** [comment]
Hold on, I didn't do this correctly.

**Comment by pdesaulniers** [comment]
Should be good now.

**Comment by grejppi** [comment]
Thank you! :tada:

**Comment by unfa** [comment]
Sweet! Thanks for bringing Bitrot to Arch, @pdesaulniers !

**Comment by pdesaulniers** [comment]
I pushed a package to the AUR: https://aur.archlinux.org/packages/bitrot-git/

**Pull request merged**
