### PR TITLE
update to use python3

### PR DESCRIPTION
**Pull request by hellocatfood**
update to use python3

### CODE REVIEW

**Comment by grejppi** [comment]
You can run waf with Python 3 already by running it with `python3 ./waf`, it just isn't the default. I personally prefer Python 3 too.

Waf however is 100% a third-party tool so the choice of the default interpreter is not mine, so I'm going to close this.

**Comment by hellocatfood** [comment]
Ah, thanks for the information.

Should running `python3 ./waf` (explicitly stating python3) be added to the documentation, since most distros have removed python 2 now.

**Comment by grejppi** [comment]
It should run it with the default interpreter, whichever it is, when run by itself 🤔 and it should be compatible with 2 and 3. Did you run into any issues with `$ ./waf`?

**Comment by hellocatfood** [comment]
When running just `./waf` I get the following error:
```
/usr/bin/env: ‘python’: No such file or directory
```

Running `python3 /.waf` works (well, I have to run `./waf configure` first but I at least don't get the above error). I'm running Ubuntu 21.10 with just python 3 installed

**Pull request closed without merging**
